package com.hd.im.commons.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HDIMProtocol.proto

public final class HDIMProtocol {
  private HDIMProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code HeadType}
   */
  public enum HeadType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOGIN = 0;</code>
     */
    LOGIN(0),
    /**
     * <code>LOGIN_RESPONSE = 1;</code>
     */
    LOGIN_RESPONSE(1),
    /**
     * <code>LOGIN_OUT = 2;</code>
     */
    LOGIN_OUT(2),
    /**
     * <code>LOGIN_OUT_RESPONSE = 3;</code>
     */
    LOGIN_OUT_RESPONSE(3),
    /**
     * <code>PING = 4;</code>
     */
    PING(4),
    /**
     * <code>PONG = 5;</code>
     */
    PONG(5),
    /**
     * <code>PUBLISH = 6;</code>
     */
    PUBLISH(6),
    /**
     * <code>PUBLISH_RESPONSE = 7;</code>
     */
    PUBLISH_RESPONSE(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>LOGIN = 0;</code>
     */
    public static final int LOGIN_VALUE = 0;
    /**
     * <code>LOGIN_RESPONSE = 1;</code>
     */
    public static final int LOGIN_RESPONSE_VALUE = 1;
    /**
     * <code>LOGIN_OUT = 2;</code>
     */
    public static final int LOGIN_OUT_VALUE = 2;
    /**
     * <code>LOGIN_OUT_RESPONSE = 3;</code>
     */
    public static final int LOGIN_OUT_RESPONSE_VALUE = 3;
    /**
     * <code>PING = 4;</code>
     */
    public static final int PING_VALUE = 4;
    /**
     * <code>PONG = 5;</code>
     */
    public static final int PONG_VALUE = 5;
    /**
     * <code>PUBLISH = 6;</code>
     */
    public static final int PUBLISH_VALUE = 6;
    /**
     * <code>PUBLISH_RESPONSE = 7;</code>
     */
    public static final int PUBLISH_RESPONSE_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static HeadType valueOf(int value) {
      return forNumber(value);
    }

    public static HeadType forNumber(int value) {
      switch (value) {
        case 0: return LOGIN;
        case 1: return LOGIN_RESPONSE;
        case 2: return LOGIN_OUT;
        case 3: return LOGIN_OUT_RESPONSE;
        case 4: return PING;
        case 5: return PONG;
        case 6: return PUBLISH;
        case 7: return PUBLISH_RESPONSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HeadType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        HeadType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HeadType>() {
            public HeadType findValueByNumber(int number) {
              return HeadType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return HDIMProtocol.getDescriptor().getEnumTypes().get(0);
    }

    private static final HeadType[] VALUES = values();

    public static HeadType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private HeadType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:HeadType)
  }

  /**
   * Protobuf enum {@code PublishType}
   */
  public enum PublishType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MS = 0;</code>
     */
    MS(0),
    /**
     * <code>MP = 1;</code>
     */
    MP(1),
    /**
     * <code>MN = 2;</code>
     */
    MN(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MS = 0;</code>
     */
    public static final int MS_VALUE = 0;
    /**
     * <code>MP = 1;</code>
     */
    public static final int MP_VALUE = 1;
    /**
     * <code>MN = 2;</code>
     */
    public static final int MN_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static PublishType valueOf(int value) {
      return forNumber(value);
    }

    public static PublishType forNumber(int value) {
      switch (value) {
        case 0: return MS;
        case 1: return MP;
        case 2: return MN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PublishType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PublishType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PublishType>() {
            public PublishType findValueByNumber(int number) {
              return PublishType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return HDIMProtocol.getDescriptor().getEnumTypes().get(1);
    }

    private static final PublishType[] VALUES = values();

    public static PublishType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PublishType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PublishType)
  }

  /**
   * Protobuf enum {@code PlatForm}
   */
  public enum PlatForm
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ANDROID = 0;</code>
     */
    ANDROID(0),
    /**
     * <code>IOS = 1;</code>
     */
    IOS(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ANDROID = 0;</code>
     */
    public static final int ANDROID_VALUE = 0;
    /**
     * <code>IOS = 1;</code>
     */
    public static final int IOS_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static PlatForm valueOf(int value) {
      return forNumber(value);
    }

    public static PlatForm forNumber(int value) {
      switch (value) {
        case 0: return ANDROID;
        case 1: return IOS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PlatForm>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PlatForm> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PlatForm>() {
            public PlatForm findValueByNumber(int number) {
              return PlatForm.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return HDIMProtocol.getDescriptor().getEnumTypes().get(2);
    }

    private static final PlatForm[] VALUES = values();

    public static PlatForm valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PlatForm(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PlatForm)
  }

  public interface LoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Login)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string token = 1;</code>
     */
    String getToken();
    /**
     * <code>optional string token = 1;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>optional bytes encryptData = 2;</code>
     */
    com.google.protobuf.ByteString getEncryptData();

    /**
     * <code>optional bytes encryptKey = 3;</code>
     */
    com.google.protobuf.ByteString getEncryptKey();
  }
  /**
   * Protobuf type {@code Login}
   */
  public  static final class Login extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Login)
      LoginOrBuilder {
    // Use Login.newBuilder() to construct.
    private Login(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Login() {
      token_ = "";
      encryptData_ = com.google.protobuf.ByteString.EMPTY;
      encryptKey_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Login(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 18: {

              encryptData_ = input.readBytes();
              break;
            }
            case 26: {

              encryptKey_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HDIMProtocol.internal_static_Login_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HDIMProtocol.internal_static_Login_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Login.class, Builder.class);
    }

    public static final int TOKEN_FIELD_NUMBER = 1;
    private volatile Object token_;
    /**
     * <code>optional string token = 1;</code>
     */
    public String getToken() {
      Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>optional string token = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENCRYPTDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString encryptData_;
    /**
     * <code>optional bytes encryptData = 2;</code>
     */
    public com.google.protobuf.ByteString getEncryptData() {
      return encryptData_;
    }

    public static final int ENCRYPTKEY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString encryptKey_;
    /**
     * <code>optional bytes encryptKey = 3;</code>
     */
    public com.google.protobuf.ByteString getEncryptKey() {
      return encryptKey_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, token_);
      }
      if (!encryptData_.isEmpty()) {
        output.writeBytes(2, encryptData_);
      }
      if (!encryptKey_.isEmpty()) {
        output.writeBytes(3, encryptKey_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, token_);
      }
      if (!encryptData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, encryptData_);
      }
      if (!encryptKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, encryptKey_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Login)) {
        return super.equals(obj);
      }
      Login other = (Login) obj;

      boolean result = true;
      result = result && getToken()
          .equals(other.getToken());
      result = result && getEncryptData()
          .equals(other.getEncryptData());
      result = result && getEncryptKey()
          .equals(other.getEncryptKey());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + ENCRYPTDATA_FIELD_NUMBER;
      hash = (53 * hash) + getEncryptData().hashCode();
      hash = (37 * hash) + ENCRYPTKEY_FIELD_NUMBER;
      hash = (53 * hash) + getEncryptKey().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Login prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Login}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Login)
        LoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HDIMProtocol.internal_static_Login_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HDIMProtocol.internal_static_Login_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Login.class, Builder.class);
      }

      // Construct using HDIMProtocol.Login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        token_ = "";

        encryptData_ = com.google.protobuf.ByteString.EMPTY;

        encryptKey_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HDIMProtocol.internal_static_Login_descriptor;
      }

      public Login getDefaultInstanceForType() {
        return Login.getDefaultInstance();
      }

      public Login build() {
        Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Login buildPartial() {
        Login result = new Login(this);
        result.token_ = token_;
        result.encryptData_ = encryptData_;
        result.encryptKey_ = encryptKey_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Login) {
          return mergeFrom((Login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Login other) {
        if (other == Login.getDefaultInstance()) return this;
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (other.getEncryptData() != com.google.protobuf.ByteString.EMPTY) {
          setEncryptData(other.getEncryptData());
        }
        if (other.getEncryptKey() != com.google.protobuf.ByteString.EMPTY) {
          setEncryptKey(other.getEncryptKey());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Login parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Login) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object token_ = "";
      /**
       * <code>optional string token = 1;</code>
       */
      public String getToken() {
        Object ref = token_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string token = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string token = 1;</code>
       */
      public Builder setToken(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 1;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 1;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString encryptData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes encryptData = 2;</code>
       */
      public com.google.protobuf.ByteString getEncryptData() {
        return encryptData_;
      }
      /**
       * <code>optional bytes encryptData = 2;</code>
       */
      public Builder setEncryptData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        encryptData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes encryptData = 2;</code>
       */
      public Builder clearEncryptData() {
        
        encryptData_ = getDefaultInstance().getEncryptData();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString encryptKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes encryptKey = 3;</code>
       */
      public com.google.protobuf.ByteString getEncryptKey() {
        return encryptKey_;
      }
      /**
       * <code>optional bytes encryptKey = 3;</code>
       */
      public Builder setEncryptKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        encryptKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes encryptKey = 3;</code>
       */
      public Builder clearEncryptKey() {
        
        encryptKey_ = getDefaultInstance().getEncryptKey();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Login)
    }

    // @@protoc_insertion_point(class_scope:Login)
    private static final Login DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Login();
    }

    public static Login getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Login>
        PARSER = new com.google.protobuf.AbstractParser<Login>() {
      public Login parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Login(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Login> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Login> getParserForType() {
      return PARSER;
    }

    public Login getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClientInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string clientId = 1;</code>
     */
    String getClientId();
    /**
     * <code>optional string clientId = 1;</code>
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <code>optional string userId = 2;</code>
     */
    String getUserId();
    /**
     * <code>optional string userId = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>optional uint32 platForm = 3;</code>
     */
    int getPlatForm();

    /**
     * <code>optional string appVersion = 4;</code>
     */
    String getAppVersion();
    /**
     * <code>optional string appVersion = 4;</code>
     */
    com.google.protobuf.ByteString
        getAppVersionBytes();
  }
  /**
   * Protobuf type {@code ClientInfo}
   */
  public  static final class ClientInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ClientInfo)
      ClientInfoOrBuilder {
    // Use ClientInfo.newBuilder() to construct.
    private ClientInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientInfo() {
      clientId_ = "";
      userId_ = "";
      platForm_ = 0;
      appVersion_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ClientInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              clientId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 24: {

              platForm_ = input.readUInt32();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              appVersion_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HDIMProtocol.internal_static_ClientInfo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HDIMProtocol.internal_static_ClientInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientInfo.class, Builder.class);
    }

    public static final int CLIENTID_FIELD_NUMBER = 1;
    private volatile Object clientId_;
    /**
     * <code>optional string clientId = 1;</code>
     */
    public String getClientId() {
      Object ref = clientId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string clientId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private volatile Object userId_;
    /**
     * <code>optional string userId = 2;</code>
     */
    public String getUserId() {
      Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLATFORM_FIELD_NUMBER = 3;
    private int platForm_;
    /**
     * <code>optional uint32 platForm = 3;</code>
     */
    public int getPlatForm() {
      return platForm_;
    }

    public static final int APPVERSION_FIELD_NUMBER = 4;
    private volatile Object appVersion_;
    /**
     * <code>optional string appVersion = 4;</code>
     */
    public String getAppVersion() {
      Object ref = appVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        appVersion_ = s;
        return s;
      }
    }
    /**
     * <code>optional string appVersion = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAppVersionBytes() {
      Object ref = appVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        appVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientId_);
      }
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userId_);
      }
      if (platForm_ != 0) {
        output.writeUInt32(3, platForm_);
      }
      if (!getAppVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, appVersion_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientId_);
      }
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userId_);
      }
      if (platForm_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, platForm_);
      }
      if (!getAppVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, appVersion_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ClientInfo)) {
        return super.equals(obj);
      }
      ClientInfo other = (ClientInfo) obj;

      boolean result = true;
      result = result && getClientId()
          .equals(other.getClientId());
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && (getPlatForm()
          == other.getPlatForm());
      result = result && getAppVersion()
          .equals(other.getAppVersion());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
      hash = (53 * hash) + getPlatForm();
      hash = (37 * hash) + APPVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getAppVersion().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ClientInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ClientInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClientInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ClientInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClientInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ClientInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ClientInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientInfo)
        ClientInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HDIMProtocol.internal_static_ClientInfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HDIMProtocol.internal_static_ClientInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientInfo.class, Builder.class);
      }

      // Construct using HDIMProtocol.ClientInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        clientId_ = "";

        userId_ = "";

        platForm_ = 0;

        appVersion_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HDIMProtocol.internal_static_ClientInfo_descriptor;
      }

      public ClientInfo getDefaultInstanceForType() {
        return ClientInfo.getDefaultInstance();
      }

      public ClientInfo build() {
        ClientInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ClientInfo buildPartial() {
        ClientInfo result = new ClientInfo(this);
        result.clientId_ = clientId_;
        result.userId_ = userId_;
        result.platForm_ = platForm_;
        result.appVersion_ = appVersion_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClientInfo) {
          return mergeFrom((ClientInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClientInfo other) {
        if (other == ClientInfo.getDefaultInstance()) return this;
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (other.getPlatForm() != 0) {
          setPlatForm(other.getPlatForm());
        }
        if (!other.getAppVersion().isEmpty()) {
          appVersion_ = other.appVersion_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ClientInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ClientInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object clientId_ = "";
      /**
       * <code>optional string clientId = 1;</code>
       */
      public String getClientId() {
        Object ref = clientId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string clientId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clientId = 1;</code>
       */
      public Builder setClientId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientId = 1;</code>
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientId = 1;</code>
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private Object userId_ = "";
      /**
       * <code>optional string userId = 2;</code>
       */
      public String getUserId() {
        Object ref = userId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public Builder setUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private int platForm_ ;
      /**
       * <code>optional uint32 platForm = 3;</code>
       */
      public int getPlatForm() {
        return platForm_;
      }
      /**
       * <code>optional uint32 platForm = 3;</code>
       */
      public Builder setPlatForm(int value) {
        
        platForm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 platForm = 3;</code>
       */
      public Builder clearPlatForm() {
        
        platForm_ = 0;
        onChanged();
        return this;
      }

      private Object appVersion_ = "";
      /**
       * <code>optional string appVersion = 4;</code>
       */
      public String getAppVersion() {
        Object ref = appVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          appVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string appVersion = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAppVersionBytes() {
        Object ref = appVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          appVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string appVersion = 4;</code>
       */
      public Builder setAppVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string appVersion = 4;</code>
       */
      public Builder clearAppVersion() {
        
        appVersion_ = getDefaultInstance().getAppVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string appVersion = 4;</code>
       */
      public Builder setAppVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appVersion_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ClientInfo)
    }

    // @@protoc_insertion_point(class_scope:ClientInfo)
    private static final ClientInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ClientInfo();
    }

    public static ClientInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientInfo>
        PARSER = new com.google.protobuf.AbstractParser<ClientInfo>() {
      public ClientInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ClientInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ClientInfo> getParserForType() {
      return PARSER;
    }

    public ClientInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 messageHead = 1;</code>
     */
    long getMessageHead();

    /**
     * <code>optional uint64 userSettingHead = 2;</code>
     */
    long getUserSettingHead();

    /**
     * <code>optional uint64 userFriendHead = 3;</code>
     */
    long getUserFriendHead();

    /**
     * <code>optional uint64 friendRequestHead = 4;</code>
     */
    long getFriendRequestHead();
  }
  /**
   * Protobuf type {@code LoginResponse}
   */
  public  static final class LoginResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginResponse)
      LoginResponseOrBuilder {
    // Use LoginResponse.newBuilder() to construct.
    private LoginResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginResponse() {
      messageHead_ = 0L;
      userSettingHead_ = 0L;
      userFriendHead_ = 0L;
      friendRequestHead_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LoginResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              messageHead_ = input.readUInt64();
              break;
            }
            case 16: {

              userSettingHead_ = input.readUInt64();
              break;
            }
            case 24: {

              userFriendHead_ = input.readUInt64();
              break;
            }
            case 32: {

              friendRequestHead_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HDIMProtocol.internal_static_LoginResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HDIMProtocol.internal_static_LoginResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LoginResponse.class, Builder.class);
    }

    public static final int MESSAGEHEAD_FIELD_NUMBER = 1;
    private long messageHead_;
    /**
     * <code>optional uint64 messageHead = 1;</code>
     */
    public long getMessageHead() {
      return messageHead_;
    }

    public static final int USERSETTINGHEAD_FIELD_NUMBER = 2;
    private long userSettingHead_;
    /**
     * <code>optional uint64 userSettingHead = 2;</code>
     */
    public long getUserSettingHead() {
      return userSettingHead_;
    }

    public static final int USERFRIENDHEAD_FIELD_NUMBER = 3;
    private long userFriendHead_;
    /**
     * <code>optional uint64 userFriendHead = 3;</code>
     */
    public long getUserFriendHead() {
      return userFriendHead_;
    }

    public static final int FRIENDREQUESTHEAD_FIELD_NUMBER = 4;
    private long friendRequestHead_;
    /**
     * <code>optional uint64 friendRequestHead = 4;</code>
     */
    public long getFriendRequestHead() {
      return friendRequestHead_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageHead_ != 0L) {
        output.writeUInt64(1, messageHead_);
      }
      if (userSettingHead_ != 0L) {
        output.writeUInt64(2, userSettingHead_);
      }
      if (userFriendHead_ != 0L) {
        output.writeUInt64(3, userFriendHead_);
      }
      if (friendRequestHead_ != 0L) {
        output.writeUInt64(4, friendRequestHead_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageHead_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, messageHead_);
      }
      if (userSettingHead_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, userSettingHead_);
      }
      if (userFriendHead_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, userFriendHead_);
      }
      if (friendRequestHead_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, friendRequestHead_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LoginResponse)) {
        return super.equals(obj);
      }
      LoginResponse other = (LoginResponse) obj;

      boolean result = true;
      result = result && (getMessageHead()
          == other.getMessageHead());
      result = result && (getUserSettingHead()
          == other.getUserSettingHead());
      result = result && (getUserFriendHead()
          == other.getUserFriendHead());
      result = result && (getFriendRequestHead()
          == other.getFriendRequestHead());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + MESSAGEHEAD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageHead());
      hash = (37 * hash) + USERSETTINGHEAD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserSettingHead());
      hash = (37 * hash) + USERFRIENDHEAD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserFriendHead());
      hash = (37 * hash) + FRIENDREQUESTHEAD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFriendRequestHead());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LoginResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoginResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoginResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoginResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoginResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LoginResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LoginResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LoginResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LoginResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginResponse)
        LoginResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HDIMProtocol.internal_static_LoginResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HDIMProtocol.internal_static_LoginResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LoginResponse.class, Builder.class);
      }

      // Construct using HDIMProtocol.LoginResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        messageHead_ = 0L;

        userSettingHead_ = 0L;

        userFriendHead_ = 0L;

        friendRequestHead_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HDIMProtocol.internal_static_LoginResponse_descriptor;
      }

      public LoginResponse getDefaultInstanceForType() {
        return LoginResponse.getDefaultInstance();
      }

      public LoginResponse build() {
        LoginResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public LoginResponse buildPartial() {
        LoginResponse result = new LoginResponse(this);
        result.messageHead_ = messageHead_;
        result.userSettingHead_ = userSettingHead_;
        result.userFriendHead_ = userFriendHead_;
        result.friendRequestHead_ = friendRequestHead_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LoginResponse) {
          return mergeFrom((LoginResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LoginResponse other) {
        if (other == LoginResponse.getDefaultInstance()) return this;
        if (other.getMessageHead() != 0L) {
          setMessageHead(other.getMessageHead());
        }
        if (other.getUserSettingHead() != 0L) {
          setUserSettingHead(other.getUserSettingHead());
        }
        if (other.getUserFriendHead() != 0L) {
          setUserFriendHead(other.getUserFriendHead());
        }
        if (other.getFriendRequestHead() != 0L) {
          setFriendRequestHead(other.getFriendRequestHead());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LoginResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LoginResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long messageHead_ ;
      /**
       * <code>optional uint64 messageHead = 1;</code>
       */
      public long getMessageHead() {
        return messageHead_;
      }
      /**
       * <code>optional uint64 messageHead = 1;</code>
       */
      public Builder setMessageHead(long value) {
        
        messageHead_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 messageHead = 1;</code>
       */
      public Builder clearMessageHead() {
        
        messageHead_ = 0L;
        onChanged();
        return this;
      }

      private long userSettingHead_ ;
      /**
       * <code>optional uint64 userSettingHead = 2;</code>
       */
      public long getUserSettingHead() {
        return userSettingHead_;
      }
      /**
       * <code>optional uint64 userSettingHead = 2;</code>
       */
      public Builder setUserSettingHead(long value) {
        
        userSettingHead_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 userSettingHead = 2;</code>
       */
      public Builder clearUserSettingHead() {
        
        userSettingHead_ = 0L;
        onChanged();
        return this;
      }

      private long userFriendHead_ ;
      /**
       * <code>optional uint64 userFriendHead = 3;</code>
       */
      public long getUserFriendHead() {
        return userFriendHead_;
      }
      /**
       * <code>optional uint64 userFriendHead = 3;</code>
       */
      public Builder setUserFriendHead(long value) {
        
        userFriendHead_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 userFriendHead = 3;</code>
       */
      public Builder clearUserFriendHead() {
        
        userFriendHead_ = 0L;
        onChanged();
        return this;
      }

      private long friendRequestHead_ ;
      /**
       * <code>optional uint64 friendRequestHead = 4;</code>
       */
      public long getFriendRequestHead() {
        return friendRequestHead_;
      }
      /**
       * <code>optional uint64 friendRequestHead = 4;</code>
       */
      public Builder setFriendRequestHead(long value) {
        
        friendRequestHead_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 friendRequestHead = 4;</code>
       */
      public Builder clearFriendRequestHead() {
        
        friendRequestHead_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:LoginResponse)
    }

    // @@protoc_insertion_point(class_scope:LoginResponse)
    private static final LoginResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LoginResponse();
    }

    public static LoginResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginResponse>
        PARSER = new com.google.protobuf.AbstractParser<LoginResponse>() {
      public LoginResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoginResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<LoginResponse> getParserForType() {
      return PARSER;
    }

    public LoginResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Login_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Login_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022HDIMProtocol.proto\"?\n\005Login\022\r\n\005token\030\001" +
      " \001(\t\022\023\n\013encryptData\030\002 \001(\014\022\022\n\nencryptKey\030" +
      "\003 \001(\014\"T\n\nClientInfo\022\020\n\010clientId\030\001 \001(\t\022\016\n" +
      "\006userId\030\002 \001(\t\022\020\n\010platForm\030\003 \001(\r\022\022\n\nappVe" +
      "rsion\030\004 \001(\t\"p\n\rLoginResponse\022\023\n\013messageH" +
      "ead\030\001 \001(\004\022\027\n\017userSettingHead\030\002 \001(\004\022\026\n\016us" +
      "erFriendHead\030\003 \001(\004\022\031\n\021friendRequestHead\030" +
      "\004 \001(\004*\207\001\n\010HeadType\022\t\n\005LOGIN\020\000\022\022\n\016LOGIN_R" +
      "ESPONSE\020\001\022\r\n\tLOGIN_OUT\020\002\022\026\n\022LOGIN_OUT_RE" +
      "SPONSE\020\003\022\010\n\004PING\020\004\022\010\n\004PONG\020\005\022\013\n\007PUBLISH\020",
      "\006\022\024\n\020PUBLISH_RESPONSE\020\007*%\n\013PublishType\022\006" +
      "\n\002MS\020\000\022\006\n\002MP\020\001\022\006\n\002MN\020\002* \n\010PlatForm\022\013\n\007AN" +
      "DROID\020\000\022\007\n\003IOS\020\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Login_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Login_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Login_descriptor,
        new String[] { "Token", "EncryptData", "EncryptKey", });
    internal_static_ClientInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ClientInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientInfo_descriptor,
        new String[] { "ClientId", "UserId", "PlatForm", "AppVersion", });
    internal_static_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginResponse_descriptor,
        new String[] { "MessageHead", "UserSettingHead", "UserFriendHead", "FriendRequestHead", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
